# Generated by Django 5.2.7 on 2025-10-22 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practiceApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='username',
        ),
    ]
