# Generated by Django 5.2.7 on 2025-10-22 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practiceApi', '0002_rename_name_userprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
